server:
  port: 2000
spring:
  application:
    name: service-provider-user
  datasource:
    url: jdbc:mysql://localhost:3306/java1
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/